# Generated by Django 6.0.2 on 2026-02-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grade',
            field=models.IntegerField(blank=True, null=True, verbose_name='Оценка'),
        ),
    ]
