# Generated by Django 6.0.2 on 2026-02-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_message_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course',
            field=models.CharField(blank=True, choices=[('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс')], max_length=1, null=True, verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='profile',
            name='group_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Группа'),
        ),
    ]
