# Generated by Django 6.0.2 on 2026-02-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_course_profile_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_typing',
            field=models.BooleanField(default=False, verbose_name='Печатает'),
        ),
    ]
