# Generated by Django 6.0.2 on 2026-02-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile_is_typing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar',
            new_name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_level',
            field=models.CharField(choices=[('BACHELOR', 'Бакалавриат'), ('MASTER', 'Магистратура'), ('PHD', 'Докторантура')], default='BACHELOR', max_length=20, verbose_name='Уровень образования'),
        ),
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('RU', 'Русский'), ('KZ', 'Казахский'), ('EN', 'Английский')], default='RU', max_length=2, verbose_name='Язык обучения'),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Срок обучения'),
        ),
    ]
