# Generated by Django 6.0.2 on 2026-02-20 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_avatar_profile_image_profile_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('target_group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Для группы (пусто = для всех)')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/', verbose_name='Материалы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект/Задание',
                'verbose_name_plural': 'Проекты/Задания',
            },
        ),
    ]
