# Generated by Django 6.0.2 on 2026-02-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_grade',
            field=models.IntegerField(default=100, verbose_name='Макс. балл'),
        ),
        migrations.AddField(
            model_name='task',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.assignment'),
        ),
    ]
