# Generated by Django 6.0.2 on 2026-02-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assignment_max_grade_task_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ученая степень'),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Кафедра'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Стаж работы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instruction_language',
            field=models.CharField(choices=[('RU', 'Русский'), ('KZ', 'Казахский'), ('EN', 'Английский')], default='RU', max_length=2, verbose_name='Язык преподавания'),
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, null=True, verbose_name='Научные интересы'),
        ),
        migrations.AddField(
            model_name='profile',
            name='office_hours',
            field=models.TextField(blank=True, null=True, verbose_name='Часы приема (подробно)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='office_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кабинет / Часы приема'),
        ),
    ]
