# Generated by Django 6.0.2 on 2026-02-21 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_profile_academic_degree_profile_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='max_grade',
            new_name='max_score',
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Для курса'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='type',
            field=models.CharField(default='word', max_length=50, verbose_name='Формат файла'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='target_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Для группы'),
        ),
    ]
