# Generated by Django 6.0.2 on 2026-02-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_max_grade_assignment_max_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='max_score',
            new_name='max_grade',
        ),
    ]
