# Generated by Django 6.0.2 on 2026-03-20 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_rename_max_score_assignment_max_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Проект/Задание', 'verbose_name_plural': 'Проекты/Задания'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='bonus_points',
            field=models.IntegerField(default=0, verbose_name='Бонусные баллы'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='difficulty',
            field=models.CharField(choices=[('Легкая', 'Легкая'), ('Средняя', 'Средняя'), ('Высокая', 'Высокая')], default='Средняя', max_length=20, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='target_course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Для курса (номер)'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='target_group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Для группы (название)'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель'),
        ),
    ]
