# Generated by Django 6.0.2 on 2026-04-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_assignment_options_assignment_bonus_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата сдачи'),
        ),
    ]
