# Generated by Django 6.0.2 on 2026-04-13 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_task_submitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AddField(
            model_name='message',
            name='is_to_admin',
            field=models.BooleanField(default=False, verbose_name='Для админа'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкая'), ('medium', 'Средняя'), ('hard', 'Высокая')], default='medium', max_length=20, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
    ]
